# Generated by Django 4.2 on 2024-01-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_storeimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeimages',
            name='boolval',
            field=models.IntegerField(default=0),
        ),
    ]
