# Generated by Django 4.2 on 2024-01-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='boolval',
            field=models.IntegerField(default=0),
        ),
    ]
