# Generated by Django 4.2 on 2024-01-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_video_boolval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcetext',
            name='text',
            field=models.CharField(max_length=100000),
        ),
    ]
