# Generated by Django 4.2 on 2024-02-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pdffile'),
        ('myapp', '0008_storepdfs'),
    ]

    operations = [
    ]
