# Generated by Django 4.2 on 2024-02-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_merge_0008_pdffile_0008_storepdfs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfFile',
        ),
        migrations.AddField(
            model_name='storeimages',
            name='text',
            field=models.CharField(default='SVEC CSE Department', max_length=500),
        ),
    ]
