# Generated by Django 4.2 on 2024-02-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_pdffile_storeimages_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepdfs',
            name='name',
            field=models.CharField(default='TimeTable', max_length=100),
        ),
    ]
