# Generated by Django 4.2 on 2024-02-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_storepdfs_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_section', models.CharField(max_length=255)),
                ('mon', models.CharField(max_length=255)),
                ('tue', models.CharField(max_length=255)),
                ('wed', models.CharField(max_length=255)),
                ('thu', models.CharField(max_length=255)),
                ('fri', models.CharField(max_length=255)),
                ('sat', models.CharField(max_length=255)),
                ('tm', models.CharField(max_length=255)),
            ],
        ),
    ]
