# Generated by Django 4.2 on 2024-02-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_section', models.CharField(max_length=255)),
                ('mon', models.CharField(max_length=255)),
                ('tue', models.CharField(max_length=255)),
                ('wed', models.CharField(max_length=255)),
                ('thu', models.CharField(max_length=255)),
                ('fri', models.CharField(max_length=255)),
                ('sat', models.CharField(max_length=255)),
                ('tm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_section', models.CharField(max_length=255)),
                ('mon', models.CharField(max_length=255)),
                ('tue', models.CharField(max_length=255)),
                ('wed', models.CharField(max_length=255)),
                ('thu', models.CharField(max_length=255)),
                ('fri', models.CharField(max_length=255)),
                ('sat', models.CharField(max_length=255)),
                ('tm', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='TimeTable',
            new_name='TimeTable2',
        ),
    ]
