# Generated by Django 4.2 on 2024-02-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_timetable3_timetable4_rename_timetable_timetable2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='val',
            field=models.IntegerField(default=0),
        ),
    ]
